export const projects = [
  {
    id: "01",
    title: "Mission100 Hospital 🏥",
    subtitle: "Production Healthcare & Preventive Health Platform",
    period: "April 2026 – Present",
    description:
      "A real-world production healthcare platform for preventive healthcare, appointments, consultations, diagnostics, wellness, and healthcare professional registrations.",
    detailDescription:
      "Mission100 Hospital is a real-world production healthcare platform developed during my web development experience. The platform focuses on preventive healthcare and wellness while providing users with access to appointments, consultations, diagnostic services, health assessments, and healthcare professionals. It also supports registrations for doctors, nutrition experts, fitness experts, yoga and wellness professionals, and other members of the healthcare ecosystem. The platform was built with a strong focus on responsive UI/UX, SEO, performance, scalable React architecture, authentication, dynamic routing, database integration, and production deployment.",
    points: [
      "Developed and maintained a real-world production healthcare platform.",
      "Implemented appointment booking and online consultation workflows.",
      "Built healthcare professional registration systems for doctors and wellness experts.",
      "Created responsive healthcare-focused interfaces for desktop, tablet, and mobile users.",
      "Integrated MongoDB for healthcare and user-related data.",
      "Implemented reusable React and Next.js architecture for scalable development.",
      "Worked on SEO, performance optimization, responsive design, and production readiness.",
      "Managed deployment and hosting workflows for the live production platform.",
      "Built healthcare service sections covering preventive care, diagnostics, heart health, mental wellness, nutrition, fitness, and Ayurveda.",
    ],
    techStack: [
      "Next.js",
      "React.js",
      "JavaScript",
      "Tailwind CSS",
      "Node.js",
      "MongoDB",
      "Authentication",
      "SEO Optimization",
    ],
    image: "/project/mission100-hospital.png",
    category: "Real World Full Stack Project",
    liveUrl: "https://mission100hospital.com",
  },

  {
    id: "02",
    title: "Delhi Angel Network 💼",
    subtitle: "Angel Investment, Startup & Mentorship Platform",
    period: "2026 – Present",
    description:
      "A professional startup and investment ecosystem platform connecting entrepreneurs with investors, mentorship, funding support, and strategic business services.",
    detailDescription:
      "Delhi Angel Network is a professional digital platform for a startup and investment ecosystem supporting entrepreneurs through funding, mentorship, strategic networking, and business services. The platform presents startup funding opportunities, investor connections, mentorship programs, pitch deck creation, financial modeling, valuation, business-plan analysis, grant support, due diligence, and entrepreneurship events. The website provides a professional digital presence for connecting founders, investors, mentors, and the wider startup ecosystem.",
    points: [
      "Developed a professional digital platform for a startup investment and mentorship ecosystem.",
      "Created responsive pages for investors, entrepreneurs, mentorship, events, services, and company information.",
      "Implemented startup funding and investor-focused user journeys.",
      "Built mentorship and business-service presentation sections.",
      "Created sections for pitch deck creation, financial modeling, valuation, business-plan analysis, grants, and due diligence services.",
      "Implemented responsive layouts optimized for desktop, tablet, and mobile devices.",
      "Built professional forms and application/contact workflows.",
      "Developed event and mentorship sections for startup ecosystem activities.",
      "Focused on modern UI/UX, accessibility, performance, and professional brand presentation.",
    ],
    techStack: [
      "Next.js",
      "React.js",
      "JavaScript",
      "Tailwind CSS",
      "Node.js",
      "MongoDB",
      "SEO Optimization",
    ],
    image: "/project/delhi-angel-network.png",
    category: "Startup & Investment Platform",
    liveUrl: "https://delhiangelnetwork.in",
  },

  {
    id: "03",
    title: "Vayu Galaxy 🚀",
    subtitle: "Futuristic Aerial Township & Innovation Platform",
    period: "2026 – Present",
    description:
      "A futuristic digital experience showcasing aerial living, advanced infrastructure, robotics, drones, and large-scale innovation projects.",
    detailDescription:
      "Vayu Galaxy is a futuristic web platform built around the vision of next-generation aerial living and large-scale technological innovation. The website presents the concept of a township in the air and showcases multiple innovation projects. The experience combines cinematic visual presentation, project storytelling, responsive layouts, animation, and modern web interactions to communicate an ambitious technology and infrastructure vision.",
    points: [
      "Developed a futuristic and cinematic website experience for Vayu Galaxy.",
      "Created a strong visual presentation around the concept of aerial living.",
      "Built dedicated sections for major innovation and technology projects.",
      "Presented robotics, drone, infrastructure, and large-scale innovation concepts.",
      "Designed responsive layouts for modern desktop and mobile experiences.",
      "Implemented animated and interactive visual sections.",
      "Created structured project and company information architecture.",
      "Focused heavily on modern UI/UX, visual storytelling, and performance.",
      "Modernized the website architecture using a contemporary React/Next.js workflow.",
    ],
    techStack: [
      "Next.js",
      "React.js",
      "JavaScript",
      "Tailwind CSS",
      "Framer Motion",
      "Responsive Design",
      "SEO Optimization",
    ],
    image: "/project/vayu-galaxy.png",
    category: "Futuristic Technology & Innovation Platform",
    liveUrl: "https://vayugalaxy.com",
  },

  {
    id: "04",
    title: "Young India Show 🇮🇳",
    subtitle: "NGO & Social Impact Platform",
    period: "April 2026 – Present",
    description:
      "A professional NGO website built for a government-registered social organization focused on social impact, awareness, campaigns, and community initiatives.",
    detailDescription:
      "Young India Show is a modern NGO platform developed for a government-registered organization focused on social impact, awareness campaigns, and community-driven initiatives. The platform provides information about the organization, missions, campaigns, events, volunteer activities, and community initiatives while maintaining a clean, accessible, and professional digital presence. The website is continuously maintained and improved with modern UI/UX practices, optimized performance, SEO, and scalable architecture.",
    points: [
      "Developed a modern and professional NGO website for a government-registered organization.",
      "Designed responsive layouts optimized for desktop, tablet, and mobile devices.",
      "Built scalable frontend architecture using reusable React components.",
      "Improved accessibility and user experience with clean navigation and UI design.",
      "Optimized website loading speed and SEO performance.",
      "Implemented dynamic sections for campaigns, missions, events, and volunteer activities.",
      "Managed and maintained the platform with continuous updates and improvements.",
    ],
    techStack: [
      "Next.js",
      "React.js",
      "JavaScript",
      "Tailwind CSS",
      "Node.js",
      "MongoDB",
    ],
    image: "/project/young-india-show.png",
    category: "NGO / Social Impact Platform",
    liveUrl: "https://youngindiashow.com",
  },

  {
    id: "05",
    title: "Punpun 📈",
    subtitle: "Full-Service Digital Marketing & Business Growth Platform",
    period: "2026 – Present",
    description:
      "A full-service digital marketing platform providing web development, app development, SEO, social media marketing, outdoor advertising, startup consultation, funding, mentorship, and business growth services.",
    detailDescription:
      "Punpun is a professional digital marketing and business growth platform providing a broad range of digital and traditional marketing services. The platform covers website development, mobile application development, SEO, social media marketing, billboard and hoarding advertising, banner advertising, startup consultation, funding support, mentorship, and other business growth services. It is designed as a one-stop digital services platform for businesses, startups, and organizations looking to build, market, and grow their presence.",
    points: [
      "Developed a professional digital marketing and business services platform.",
      "Presented website and web application development services.",
      "Presented mobile application development services.",
      "Included SEO and search visibility services.",
      "Included social media marketing and digital marketing services.",
      "Presented billboard, banner, hoarding, and outdoor advertising services.",
      "Included startup consultation and business growth support.",
      "Presented funding and mentorship opportunities for startups.",
      "Created a unified platform covering both digital and traditional marketing services.",
      "Designed the platform to serve businesses, startups, and organizations under one digital services ecosystem.",
    ],
    techStack: [
      "Web Development",
      "App Development",
      "SEO",
      "Social Media Marketing",
      "Digital Marketing",
      "Outdoor Advertising",
      "Startup Consulting",
    ],
    image: "/project/punpun.png",
    category: "Digital Marketing & Business Growth Platform",
    liveUrl: "https://punpun.in",
  },

  {
    id: "06",
    title: "Mission100 Hospital App 📱",
    subtitle: "Healthcare Mobile Application",
    period: "2026 – Present",
    description:
      "The official Mission100 Hospital mobile application extending the healthcare platform to Android users.",
    detailDescription:
      "Mission100 Hospital App is the official mobile application for the Mission100 Hospital healthcare ecosystem. The application extends the Mission100 digital healthcare experience to Android users and provides mobile access to the platform's healthcare services. The application was initially released through closed testing and has now been publicly launched on Google Play Store.",
    points: [
      "Developed the mobile application for the Mission100 Hospital healthcare ecosystem.",
      "Extended the Mission100 healthcare experience from web to mobile.",
      "Built the application for Android users.",
      "Connected the mobile experience with the broader Mission100 healthcare ecosystem.",
      "Focused on a user-friendly and accessible healthcare experience.",
      "Successfully moved the application from closed testing to public production release.",
      "Published the application on Google Play Store for public users.",
    ],
    techStack: [
      "Mobile Application Development",
      "Android",
      "API Integration",
    ],
    image: "/project/mission100-hospital-app.png",
    category: "Healthcare Mobile Application",
    liveUrl:
      "https://play.google.com/store/apps/details?id=com.mission100.mobile",
  },

  {
    id: "07",
    title: "Get Me A Chai ☕",
    subtitle: "Crowdfunding & Creator Support Platform",
    period: "December 2025 – January 2026",
    description:
      "A Patreon-inspired crowdfunding platform where creators receive support from their audience through secure online payments.",
    detailDescription:
      "Get Me A Chai is a full-stack crowdfunding platform inspired by Patreon and Buy Me a Coffee. The application allows creators to receive donations and support from their followers through secure payment integration. It includes authentication systems, responsive dashboards, payment tracking, and modern UI/UX practices. The project demonstrates frontend and backend development skills along with third-party payment gateway integration.",
    points: [
      "Integrated Razorpay payment gateway for secure online donations.",
      "Implemented authentication and protected user sessions using NextAuth.",
      "Designed responsive creator dashboards for managing supporters and contributions.",
      "Built reusable React components for scalability and maintainability.",
      "Integrated MongoDB database for storing user and payment information.",
      "Created responsive user interfaces using Tailwind CSS.",
      "Implemented notifications and loading states for improved user experience.",
    ],
    techStack: [
      "Next.js",
      "React.js",
      "MongoDB",
      "Node.js",
      "Tailwind CSS",
      "Razorpay",
      "NextAuth",
    ],
    image: "/project/get-me-a-chai.png",
    category: "Full Stack Crowdfunding Platform",
    liveUrl: "https://get-me-a-chai-hemant.vercel.app/",
  },

  {
    id: "08",
    title: "Hemant Pandey Portfolio 💻",
    subtitle: "Personal Developer Portfolio",
    period: "2026 – Present",
    description:
      "A modern developer portfolio showcasing my projects, technical skills, professional experience, education, and software development work.",
    detailDescription:
      "Hemant Pandey Portfolio is my personal developer portfolio built to present my software development work, technical skills, professional experience, projects, education, services, and credentials in a modern digital format. The portfolio uses a data-driven project architecture with dedicated project detail pages, responsive layouts, dynamic SEO metadata, Open Graph cards, structured data, animations, and an integrated AI assistant context system.",
    points: [
      "Designed and developed a modern personal developer portfolio.",
      "Built a data-driven project system for scalable portfolio management.",
      "Implemented dedicated dynamic project detail pages.",
      "Implemented dynamic SEO titles, descriptions, canonical URLs, Open Graph metadata, and structured data.",
      "Built responsive layouts for desktop, tablet, and mobile devices.",
      "Implemented Framer Motion animations and interactive project transitions.",
      "Created reusable React components for portfolio sections.",
      "Integrated an AI assistant with dynamically generated portfolio context.",
      "Implemented a reusable design system for consistent visual presentation.",
    ],
    techStack: [
      "React.js",
      "Vite",
      "JavaScript",
      "Tailwind CSS",
      "Framer Motion",
      "React Router",
      "React Helmet Async",
      "Lucide React",
    ],
    image: "/project/portfolio-hemantpandey.png",
    category: "Personal Developer Portfolio",
    liveUrl: "https://hemantpandey.in",
  },

  {
    id: "09",
    title: "Mail.HemantPandey.in ✉️",
    subtitle: "Free Custom-Domain Email Platform",
    period: "2026 – Present",
    description:
      "A personal Gmail replacement that provides free custom-domain email sending and receiving with unlimited domain-based addresses.",
    detailDescription:
      "Mail.HemantPandey.in is my personal custom-domain email platform built as a free alternative to traditional personal email services. It allows me to create and use domain-based email addresses such as hello@hemantpandey.in and hi@hemantpandey.in without paying separately for each mailbox. The platform supports sending and receiving emails, composing messages, inbox management, deleting emails, and maintaining email records. It also integrates email synchronization and backup workflows with Gmail while using cloud-based hosting and email infrastructure.",
    points: [
      "Built a personal Gmail replacement using the hemantpandey.in domain.",
      "Enabled custom-domain email addresses such as hello@hemantpandey.in and hi@hemantpandey.in.",
      "Implemented free email sending and receiving using custom domain addresses.",
      "Allowed receiving emails from external users on domain-based addresses.",
      "Built email composition and sending functionality.",
      "Implemented inbox and received-email management.",
      "Implemented email deletion and email record management.",
      "Integrated Gmail synchronization and backup workflows.",
      "Maintained email records and backups through cloud infrastructure.",
      "Configured the platform around a custom email domain and personal web infrastructure.",
    ],
    techStack: [
      "Web Application",
      "Cloudflare",
      "Vercel",
      "Custom Domain",
      "Email Infrastructure",
      "Gmail Integration",
      "Email APIs",
    ],
    image: "/project/mail-system.png",
    category: "Email & Cloud Infrastructure Platform",
    liveUrl: "https://mail.hemantpandey.in",
  },

  {
    id: "10",
    title: "PassOP 🔐",
    subtitle: "Secure Password Manager",
    period: "November 2025 – December 2025",
    description:
      "A secure password manager application for storing and organizing credentials.",
    detailDescription:
      "PassOP is a secure password management application that allows users to store, organize, edit, and manage their credentials efficiently. The project focuses on simplicity, responsive UI design, and smooth user experience while integrating MongoDB for persistent password storage and modern frontend architecture.",
    points: [
      "Implemented CRUD operations for password management.",
      "Built copy-to-clipboard functionality for quick credential access.",
      "Designed responsive and minimal user interfaces using Tailwind CSS.",
      "Integrated MongoDB for persistent password storage and management.",
      "Added password visibility toggles and search/filtering functionality.",
      "Optimized frontend interactions using React state management.",
      "Created reusable UI components for scalability and cleaner architecture.",
    ],
    techStack: [
      "React.js",
      "JavaScript",
      "Tailwind CSS",
      "MongoDB",
      "Node.js",
    ],
    image: "/project/passop.png",
    category: "Full Stack Security Application",
    liveUrl: "https://passop-by-hemant.vercel.app/",
  },

  {
    id: "11",
    title: "MusicPlayNest 🎵",
    subtitle: "Music Streaming & Audio Platform",
    period: "November 2025 – January 2026",
    description:
      "A modern music streaming platform with playlists and dynamic audio playback.",
    detailDescription:
      "MusicPlayNest is an interactive music streaming application inspired by modern music platforms. Users can browse playlists, play songs dynamically, and enjoy a responsive and immersive audio experience. The project demonstrates frontend UI/UX expertise, dynamic rendering, audio handling, and scalable component architecture.",
    points: [
      "Built a fully functional music player with playback controls.",
      "Implemented dynamic playlist and song management functionality.",
      "Created responsive and visually modern user interfaces.",
      "Integrated smooth audio playback using HTML5 Audio APIs.",
      "Developed reusable and scalable React components.",
      "Optimized rendering performance for seamless music interactions.",
      "Added dynamic music handling and modern frontend transitions.",
    ],
    techStack: [
      "React.js",
      "JavaScript",
      "Tailwind CSS",
      "HTML5 Audio API",
    ],
    image: "/project/music-play-nest.png",
    category: "Frontend + Backend Music Platform",
    liveUrl: "https://musicplaynest.vercel.app/",
  },

  {
    id: "12",
    title: "Todo By Hemant ✅",
    subtitle: "Task & Productivity Management App",
    period: "January 2026",
    description:
      "A clean and responsive productivity application for managing daily tasks efficiently.",
    detailDescription:
      "Todo By Hemant is a productivity-focused task management application designed to help users organize their daily workflow efficiently. The application provides task creation, editing, filtering, and completion tracking functionality with a clean and responsive user interface.",
    points: [
      "Implemented task creation, editing, deletion, and completion tracking.",
      "Designed minimal and responsive interfaces using Tailwind CSS.",
      "Integrated local storage for persistent task management.",
      "Built filtering functionality for completed and pending tasks.",
      "Used React hooks and state management for dynamic updates.",
      "Created reusable frontend components for maintainability.",
    ],
    techStack: [
      "React.js",
      "JavaScript",
      "Tailwind CSS",
      "Local Storage",
    ],
    image: "/project/itask.png",
    category: "Frontend Productivity Application",
    liveUrl: "https://todo-byhemant.vercel.app/",
  },
];